CREATE TABLE DEMO (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(255) NOT NULL,
    DESCRIPTION   VARCHAR2(1000),
    CREATED_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
